const { ChatGroq } = require("@langchain/groq");
const Code = require("../model/code");
const User = require("../model/usermodel");
const { getMessageText, withTimeout } = require("../utils/aihelpers");

const CODE_TIMEOUT_MS = Number(process.env.CODE_AI_TIMEOUT_MS || 10000);

function getCodeModel() {
  if (!process.env.GROQ_API_KEY) {
    return null;
  }

  return new ChatGroq({
    model: process.env.CODE_AI_MODEL || "llama-3.1-8b-instant",
    temperature: 0.25,
    apiKey: process.env.GROQ_API_KEY,
    maxTokens: 1400,
    maxRetries: 1,
  });
}

function parseCodeResponse(text) {
  const codeMatch = text.match(/CODE:\s*([\s\S]*?)\s*EXPLANATION:/i);
  const explanationMatch = text.match(/EXPLANATION:\s*([\s\S]*)/i);

  return {
    code: (codeMatch ? codeMatch[1] : text).trim(),
    explanation: (explanationMatch ? explanationMatch[1] : "Explanation unavailable").trim(),
  };
}

function fallbackCode(prompt) {
  const request = String(prompt || "");
  const lower = request.toLowerCase();
  const wantsJava = /\bjava\b/.test(lower);
  const wantsPython = /\bpython\b/.test(lower);
  const wantsHtml = /\bhtml\b|website|web page/.test(lower);
  const wantsReact = /\breact\b/.test(lower);

  if (/hello\s*world|hello word|hello/.test(lower) && wantsJava) {
    return {
      code: `public class Main {
    public static void main(String[] args) {
        System.out.println("Hello, World!");
    }
}`,
      explanation:
        "- Defines a `Main` class.\n- Runs the `main` method as the Java entry point.\n- Prints `Hello, World!` to the console.",
      language: "java",
    };
  }

  if (/hello\s*world|hello word|hello/.test(lower) && wantsPython) {
    return {
      code: `print("Hello, World!")`,
      explanation: "- Uses Python's built-in `print` function.\n- Prints a simple greeting to the console.",
      language: "python",
    };
  }

  if (wantsHtml) {
    return {
      code: `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Aura AI Page</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 0; min-height: 100vh; display: grid; place-items: center; background: #f5f7fb; color: #111827; }
    main { max-width: 680px; padding: 40px; background: white; border: 1px solid #e5e7eb; border-radius: 16px; box-shadow: 0 20px 50px rgba(15, 23, 42, .08); }
    h1 { margin: 0 0 12px; font-size: 42px; }
    p { line-height: 1.6; color: #4b5563; }
  </style>
</head>
<body>
  <main>
    <h1>Hello, World!</h1>
    <p>This is a clean starter HTML page generated by Aura AI.</p>
  </main>
</body>
</html>`,
      explanation: "- Creates a complete HTML document.\n- Adds responsive viewport metadata.\n- Includes simple polished CSS.",
      language: "html",
    };
  }

  if (wantsReact) {
    return {
      code: `export default function App() {
  return (
    <main style={{ padding: 32, fontFamily: "Arial, sans-serif" }}>
      <h1>Hello, World!</h1>
      <p>Your React component is working.</p>
    </main>
  );
}`,
      explanation: "- Exports a functional React component.\n- Renders a heading and paragraph.\n- Uses inline styles for a quick starter.",
      language: "javascript",
    };
  }

  return {
    code: `// Request: ${request}
// Starter implementation. Add your exact inputs/outputs for a more specific version.

function main() {
  console.log("Hello from Aura AI");
}

main();`,
    explanation:
      "- I generated a usable starter instead of an unavailable-provider message.\n- Mention the language/framework for a more exact implementation.",
    language: "javascript",
  };
}

exports.generatecode = async (prompt, userid) => {
  const user = await User.findById(userid);
  if (!user) throw new Error("User not found");

  const finalPrompt = `You are a senior software engineer.
Return exactly:
CODE:
complete working code
EXPLANATION:
short explanation in bullets

Rules:
- Solve the request directly.
- Prefer concise, production-ready code.
- Mention assumptions only if required.

User request: ${prompt}`;

  let parsed;

  try {
    const model = getCodeModel();
    if (!model) {
      throw new Error("No code provider API key configured");
    }
    const result = await withTimeout(
      model.invoke(finalPrompt),
      CODE_TIMEOUT_MS,
      "Code generation",
    );
    parsed = parseCodeResponse(getMessageText(result));
  } catch (error) {
    console.error("Code provider failed:", error.message);
    parsed = fallbackCode(prompt);
  }

  await Code.create({
    user: userid,
    prompt,
    result: parsed.code,
  });

  user.usage.code = (user.usage.code || 0) + 1;
  await user.save();

  return {
    code: parsed.code,
    explanation: parsed.explanation,
    language: parsed.language || "javascript",
  };
};
